services:
  - type: web
    name: email-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn email_agent.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: email_agent.settings
      - key: PYTHON_VERSION
        value: 3.11
